# Generated by Django 6.0.5 on 2026-09-20 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_alter_coupon_maximum_discount_amount'),
        ('students', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_coupons', to='students.cart')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_applications', to='admins.coupon')),
            ],
            options={
                'db_table': 'student_cart_coupon',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('cart', 'coupon'), name='unique_cart_coupon')],
            },
        ),
    ]
