# Generated by Django 5.2.7 on 2026-09-21 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0014_coupon_total_discount_given'),
        ('students', '0005_cartcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartcoupon',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_coupon_applications', to='admins.batch'),
        ),
        migrations.AddConstraint(
            model_name='cartcoupon',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', False)), fields=('cart', 'batch'), name='unique_cart_coupon_batch'),
        ),
    ]
