# Generated by Django 6.0.5 on 2026-09-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_cartcoupon_batch_cartcoupon_unique_cart_coupon_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='neo_student_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=15, null=True, unique=True),
        ),
    ]
