# Generated by Django 6.0.5 on 2026-09-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentprofile_neo_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='neo_student_id',
            field=models.CharField(db_index=True, editable=False, max_length=15, unique=True),
        ),
    ]
