# Generated by Django 5.2.7 on 2026-10-09 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_quizquestion_marks_and_more'),
        ('students', '0008_alter_studentprofile_neo_student_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title_snapshot', models.CharField(max_length=100)),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('timed_out', 'Timed Out')], db_index=True, default='in_progress', max_length=20)),
                ('answering_time_minutes_snapshot', models.PositiveIntegerField()),
                ('maximum_attempts_snapshot', models.PositiveIntegerField()),
                ('marks_per_question_snapshot', models.PositiveIntegerField()),
                ('maximum_marks', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attempts', to='courses.chapterquiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_quiz_attempt',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_snapshot_key', models.CharField(max_length=64)),
                ('question_text_snapshot', models.TextField()),
                ('options_snapshot', models.JSONField(default=list)),
                ('correct_option_label_snapshot', models.CharField(max_length=1)),
                ('selected_option_label', models.CharField(blank=True, default='', max_length=1)),
                ('selected_option_text_snapshot', models.TextField(blank=True, default='')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_awarded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='students.quizattempt')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attempt_answers', to='courses.quizquestion')),
            ],
            options={
                'db_table': 'student_quiz_attempt_answer',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'status'], name='stu_quiz_attempt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'status'], name='quiz_attempt_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('quiz__isnull', False)), fields=('student', 'quiz', 'attempt_number'), name='unique_student_quiz_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='quizattemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question_snapshot_key'), name='unique_attempt_question_snapshot'),
        ),
    ]
