# Generated by Django 5.2.7 on 2026-06-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=200, unique=True)),
                ('batch_description', models.TextField()),
                ('batch_thumbnail', models.ImageField(upload_to='batch_thumbnails/')),
                ('batch_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
