# Generated by Django 6.0.5 on 2026-07-25 01:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_batch_marketplace_visible_alter_batch_batch_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='batch_price',
            new_name='original_price',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='marketplace_visible',
        ),
        migrations.AddField(
            model_name='batch',
            name='admission_close_datetime',
            field=models.DateTimeField(blank=True, help_text='Leave blank to keep admissions open.', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='course_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='discount_type',
            field=models.CharField(choices=[('none', 'No Discount'), ('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='batch',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='batch',
            name='offer_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='offer_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='publish_datetime',
            field=models.DateTimeField(blank=True, help_text='Required only for scheduled publishing.', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='publish_type',
            field=models.CharField(choices=[('immediate', 'Publish Immediately'), ('scheduled', 'Schedule Publish')], default='immediate', max_length=20),
        ),
        migrations.AddField(
            model_name='batch',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Actual time when the batch becomes live.', null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='batch_thumbnail'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_status'], name='admins_batc_batch_s_a81269_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['publish_datetime'], name='admins_batc_publish_2ae500_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['admission_close_datetime'], name='admins_batc_admissi_7cd17c_idx'),
        ),
    ]
