# Generated by Django 5.2.7 on 2026-07-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_rename_batch_price_batch_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='marketplace_visible',
            field=models.BooleanField(default=True),
        ),
    ]
