# Generated by Django 6.0.5 on 2026-07-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_batch_featured_batch_marketplace_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
