# Generated by Django 5.2.7 on 2026-09-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_batch_final_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique coupon code, for example NEO10.', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Internal description of this coupon.')),
                ('coupon_type', models.CharField(choices=[('general', 'General Coupon'), ('batch_specific', 'Batch-Specific Coupon')], db_index=True, default='general', max_length=20)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart/order amount required to use this coupon.', max_digits=10)),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount allowed for percentage coupons. Leave blank for no maximum.', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(help_text='Date and time from which the coupon becomes valid.')),
                ('valid_until', models.DateTimeField(help_text='Date and time after which the coupon expires.')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum total number of successful uses. Leave blank for unlimited usage.', null=True)),
                ('per_user_limit', models.PositiveIntegerField(blank=True, help_text='Maximum successful uses per student. Leave blank for unlimited usage.', null=True)),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, help_text='Number of successful coupon uses.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_batches', models.ManyToManyField(blank=True, help_text='Select the batches for a batch-specific coupon. Leave empty for general coupons.', related_name='coupons', to='admins.batch')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coupon_type'], name='admins_coup_coupon__8a8ae1_idx'), models.Index(fields=['is_active'], name='admins_coup_is_acti_e952ec_idx'), models.Index(fields=['valid_from'], name='admins_coup_valid_f_2c31a7_idx'), models.Index(fields=['valid_until'], name='admins_coup_valid_u_2f1f8d_idx')],
            },
        ),
    ]
