# Generated by Django 6.0.5 on 2026-09-11 02:08

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_batches',
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional promotional image for this coupon.', max_length=255, null=True, verbose_name='coupon_thumbnail'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='maximum_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum current selling price allowed for a general coupon.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique coupon code, for example NEO30.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage value or fixed discount amount.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='maximum_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount allowed for percentage coupons. Maximum permitted value is ₹1,000.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum current selling price required for a general coupon.', max_digits=10),
        ),
        migrations.CreateModel(
            name='CouponBatchRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether this coupon is enabled for this batch.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_rules', to='admins.batch')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_rules', to='admins.coupon')),
            ],
            options={
                'verbose_name': 'Coupon Batch Rule',
                'verbose_name_plural': 'Coupon Batch Rules',
                'ordering': ['batch__batch_name'],
                'indexes': [models.Index(fields=['coupon', 'is_enabled'], name='admins_coup_coupon__cd45ff_idx'), models.Index(fields=['batch', 'is_enabled'], name='admins_coup_batch_i_a0bc16_idx')],
                'constraints': [models.UniqueConstraint(fields=('coupon', 'batch'), name='unique_coupon_batch_rule')],
            },
        ),
    ]
