# Generated by Django 6.0.5 on 2026-09-12 01:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_remove_coupon_applicable_batches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Promotional image for this coupon.', max_length=255, null=True, verbose_name='coupon_thumbnail'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='maximum_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount allowed for percentage coupons. The maximum permitted value is ₹1,000.', max_digits=10, null=True),
        ),
    ]
