# Generated by Django 6.0.5 on 2026-09-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_alter_coupon_coupon_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponbatchrule',
            options={'ordering': ['-created_at'], 'verbose_name': 'Coupon Batch Rule', 'verbose_name_plural': 'Coupon Batch Rules'},
        ),
        migrations.RemoveIndex(
            model_name='couponbatchrule',
            name='admins_coup_coupon__cd45ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='couponbatchrule',
            name='admins_coup_batch_i_a0bc16_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='coupon_type_idx',
            old_name='admins_coup_coupon__8a8ae1_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='coupon_active_idx',
            old_name='admins_coup_is_acti_e952ec_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='coupon_valid_from_idx',
            old_name='admins_coup_valid_f_2c31a7_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='coupon_valid_until_idx',
            old_name='admins_coup_valid_u_2f1f8d_idx',
        ),
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='couponbatchrule',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable this coupon for this batch.'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status'], name='coupon_status_idx'),
        ),
    ]
