# Generated by Django 6.0.5 on 2026-09-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_alter_couponbatchrule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='maximum_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy field — no longer used.', max_digits=10, null=True),
        ),
    ]
