# Generated by Django 6.0.5 on 2026-09-20 14:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_alter_coupon_maximum_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='marketplace_visible',
            field=models.BooleanField(default=True, help_text="Controls whether a batch-specific coupon is shown in the student's available coupon list. Manual coupon-code entry can still be used when the coupon is otherwise valid."),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('general', 'General Coupon'), ('batch_specific', 'Batch-Specific Coupon'), ('multi_checkout', 'Multi Checkout Coupon')], db_index=True, default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='maximum_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For General Coupon: maximum order amount. For Multi Checkout Coupon: maximum combined checkout amount.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='For General Coupon: minimum order amount. For Multi Checkout Coupon: minimum combined checkout amount.', max_digits=10),
        ),
    ]
