# Generated by Django 5.2.7 on 2026-09-21 07:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_coupon_marketplace_visible_alter_coupon_coupon_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='total_discount_given',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Actual total discount granted across successful coupon checkouts.', max_digits=12),
        ),
    ]
