# Generated by Django 6.0.5 on 2026-09-28 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0014_coupon_total_discount_given'),
        ('orders', '0005_ordercoupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOrderSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_order_selections', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_selections', to='orders.order')),
            ],
            options={
                'ordering': ['-selected_at'],
                'indexes': [models.Index(fields=['admin', 'selected_at'], name='admins_admi_admin_i_ebeac5_idx')],
                'constraints': [models.UniqueConstraint(fields=('admin', 'order'), name='unique_admin_order_selection')],
            },
        ),
    ]
