# Generated by Django 6.0.5 on 2026-08-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechapter',
            name='chapter_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
