# Generated by Django 6.0.5 on 2026-08-17 02:01

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_batch_final_price'),
        ('teachers', '0002_coursechapter_chapter_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('order_changed', 'Order Changed'), ('status_changed', 'Status Changed'), ('delete_requested', 'Delete Requested'), ('delete_approved', 'Delete Approved'), ('delete_rejected', 'Delete Rejected'), ('restored', 'Restored')], max_length=30)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapter_change_logs', to='admins.teacher')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='teachers.coursechapter')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChapterVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('video_description', models.TextField(blank=True)),
                ('video_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('video_order', models.PositiveIntegerField(default=1)),
                ('delete_requested', models.BooleanField(default=False)),
                ('delete_requested_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.TextField(blank=True)),
                ('delete_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='teachers.coursechapter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_videos', to='admins.teacher')),
                ('delete_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_delete_requests', to='admins.teacher')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_videos', to='admins.teacher')),
            ],
            options={
                'ordering': ['video_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VideoChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('name_changed', 'Name Changed'), ('description_changed', 'Description Changed'), ('file_changed', 'Video File Changed'), ('order_changed', 'Order Changed'), ('delete_requested', 'Delete Requested'), ('delete_approved', 'Delete Approved'), ('delete_rejected', 'Delete Rejected'), ('restored', 'Restored')], max_length=40)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_change_logs', to='admins.teacher')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='teachers.chaptervideo')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='chaptervideo',
            index=models.Index(fields=['chapter', 'video_order'], name='teachers_ch_chapter_e37903_idx'),
        ),
    ]
