# Generated by Django 6.0.5 on 2026-08-20 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_batch_final_price'),
        ('teachers', '0003_chapterchangelog_chaptervideo_videochangelog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursechapter',
            options={'ordering': ['chapter_order', 'id']},
        ),
        migrations.AlterField(
            model_name='videochangelog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('name_changed', 'Name Changed'), ('description_changed', 'Description Changed'), ('file_changed', 'File Changed'), ('order_changed', 'Order Changed'), ('delete_requested', 'Delete Requested'), ('delete_approved', 'Delete Approved'), ('delete_rejected', 'Delete Rejected'), ('restored', 'Restored')], max_length=40),
        ),
        migrations.CreateModel(
            name='ChapterPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=255)),
                ('pdf_description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(upload_to='course_pdfs/')),
                ('pdf_order', models.PositiveIntegerField(default=1)),
                ('delete_requested', models.BooleanField(default=False)),
                ('delete_requested_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.TextField(blank=True)),
                ('delete_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='teachers.coursechapter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pdfs', to='admins.teacher')),
                ('delete_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_delete_requests', to='admins.teacher')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_pdfs', to='admins.teacher')),
            ],
            options={
                'ordering': ['pdf_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChapterQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=255)),
                ('quiz_description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('passing_percentage', models.PositiveIntegerField(default=40)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('randomize_questions', models.BooleanField(default=False)),
                ('show_result_immediately', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='teachers.coursechapter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_quizzes', to='admins.teacher')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_quizzes', to='admins.teacher')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('meeting_url', models.URLField(blank=True, max_length=1000)),
                ('meeting_id', models.CharField(blank=True, max_length=255)),
                ('meeting_password', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='teachers.coursechapter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_live_classes', to='admins.teacher')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_live_classes', to='admins.teacher')),
            ],
            options={
                'ordering': ['-scheduled_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LiveClassChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('scheduled', 'Scheduled'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('restored', 'Restored')], max_length=40)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_class_change_logs', to='admins.teacher')),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='teachers.liveclass')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PDFChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('name_changed', 'Name Changed'), ('description_changed', 'Description Changed'), ('file_changed', 'File Changed'), ('order_changed', 'Order Changed'), ('delete_requested', 'Delete Requested'), ('delete_approved', 'Delete Approved'), ('delete_rejected', 'Delete Rejected'), ('restored', 'Restored')], max_length=40)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdf_change_logs', to='admins.teacher')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='teachers.chapterpdf')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveBigIntegerField()),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('passed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='in_progress', max_length=20)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='teachers.chapterquiz')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuizChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('published', 'Published'), ('archived', 'Archived'), ('question_added', 'Question Added'), ('question_updated', 'Question Updated'), ('question_deleted', 'Question Deleted'), ('restored', 'Restored')], max_length=40)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_change_logs', to='admins.teacher')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='teachers.chapterquiz')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('true_false', 'True / False')], default='single', max_length=20)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('question_order', models.PositiveIntegerField(default=1)),
                ('explanation', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='teachers.chapterquiz')),
            ],
            options={
                'ordering': ['question_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('option_order', models.PositiveIntegerField(default=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='teachers.quizquestion')),
            ],
            options={
                'ordering': ['option_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='teachers.quizattempt')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='selected_answers', to='teachers.quizoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='teachers.quizquestion')),
            ],
        ),
        migrations.AddIndex(
            model_name='chapterpdf',
            index=models.Index(fields=['chapter', 'pdf_order'], name='teachers_ch_chapter_b75c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclass',
            index=models.Index(fields=['chapter', 'scheduled_start'], name='teachers_li_chapter_2f88b1_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz', 'question_order'], name='teachers_qu_quiz_id_147f5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_quiz_answer_per_question'),
        ),
    ]
