# Generated by Django 6.0.5 on 2026-08-22 07:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_coursechapter_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterquiz',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='chapterquiz',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='chapterquiz',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizchangelog',
            name='quiz',
        ),
        migrations.RemoveIndex(
            model_name='liveclass',
            name='teachers_li_chapter_2f88b1_idx',
        ),
        migrations.RemoveField(
            model_name='liveclasschangelog',
            name='live_class',
        ),
        migrations.RemoveField(
            model_name='liveclasschangelog',
            name='changed_by',
        ),
        migrations.RemoveConstraint(
            model_name='quizanswer',
            name='unique_quiz_answer_per_question',
        ),
        migrations.RemoveField(
            model_name='quizchangelog',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='quizoption',
            name='question',
        ),
        migrations.RemoveIndex(
            model_name='quizquestion',
            name='teachers_qu_quiz_id_147f5c_idx',
        ),
        migrations.AlterModelOptions(
            name='coursechapter',
            options={'ordering': ['chapter_order']},
        ),
        migrations.AddField(
            model_name='chapterpdf',
            name='pdf_thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pdf_thumbnail'),
        ),
        migrations.AlterField(
            model_name='chapterpdf',
            name='pdf_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pdfchangelog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('name_changed', 'Name Changed'), ('description_changed', 'Description Changed'), ('file_changed', 'PDF File Changed'), ('thumbnail_changed', 'Thumbnail Changed'), ('order_changed', 'Order Changed'), ('delete_requested', 'Delete Requested'), ('delete_approved', 'Delete Approved'), ('delete_rejected', 'Delete Rejected'), ('restored', 'Restored')], max_length=40),
        ),
        migrations.AlterField(
            model_name='videochangelog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('name_changed', 'Name Changed'), ('description_changed', 'Description Changed'), ('file_changed', 'Video File Changed'), ('order_changed', 'Order Changed'), ('delete_requested', 'Delete Requested'), ('delete_approved', 'Delete Approved'), ('delete_rejected', 'Delete Rejected'), ('restored', 'Restored')], max_length=40),
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='LiveClassChangeLog',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='selected_options',
        ),
        migrations.DeleteModel(
            name='QuizChangeLog',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='LiveClass',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
        migrations.DeleteModel(
            name='QuizOption',
        ),
        migrations.DeleteModel(
            name='ChapterQuiz',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
