# Generated by Django 6.0.5 on 2026-08-23 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_chapterquiz_quizchangelog_quizquestion_quizoption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterchangelog',
            name='changed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_chapter_change_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdfchangelog',
            name='changed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_pdf_change_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizchangelog',
            name='changed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_quiz_change_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videochangelog',
            name='changed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_video_change_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
