# Generated by Django 6.0.5 on 2026-08-23 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_batch_final_price'),
        ('teachers', '0007_chapterchangelog_changed_by_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterpdf',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_created_pdfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapterpdf',
            name='updated_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_updated_pdfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapterquiz',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_created_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapterquiz',
            name='updated_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_updated_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chaptervideo',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_created_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chaptervideo',
            name='updated_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_updated_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_created_chapters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='updated_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_updated_chapters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapterchangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chapter_change_logs', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chapterpdf',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_pdfs', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chapterpdf',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_pdfs', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_quizzes', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_quizzes', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chaptervideo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_videos', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chaptervideo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_videos', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_chapters', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_chapters', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='pdfchangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pdf_change_logs', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='quizchangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz_change_logs', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='videochangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='video_change_logs', to='admins.teacher'),
        ),
        migrations.CreateModel(
            name='DeletionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('chapter', 'Chapter'), ('video', 'Video'), ('pdf', 'PDF'), ('quiz', 'Quiz')], max_length=20)),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_name', models.CharField(max_length=255)),
                ('batch_name', models.CharField(blank=True, max_length=255)),
                ('subject_name', models.CharField(blank=True, max_length=255)),
                ('chapter_name', models.CharField(blank=True, max_length=255)),
                ('created_at_original', models.DateTimeField(blank=True, null=True)),
                ('delete_requested_at', models.DateTimeField(blank=True, null=True)),
                ('delete_request_reason', models.TextField(blank=True)),
                ('approval_reason', models.TextField(blank=True)),
                ('admin_delete_reason', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('deleted', 'Permanently Deleted'), ('rejected', 'Deletion Rejected')], default='deleted', max_length=20)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('approved_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_audits_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_audits_created', to=settings.AUTH_USER_MODEL)),
                ('created_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_audits_created', to='admins.teacher')),
                ('delete_requested_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_audits_requested', to='admins.teacher')),
                ('deleted_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_audits_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at', '-id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='teachers_de_content_8c15f3_idx'), models.Index(fields=['status', 'deleted_at'], name='teachers_de_status_f7c161_idx')],
            },
        ),
    ]
