# Generated by Django 6.0.5 on 2026-08-27 01:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_batch_final_price'),
        ('teachers', '0008_chapterpdf_created_by_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deletionaudit',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='deletionaudit',
            name='teachers_de_status_f7c161_idx',
        ),
        migrations.RenameField(
            model_name='deletionaudit',
            old_name='approval_reason',
            new_name='admin_response',
        ),
        migrations.AddField(
            model_name='deletionaudit',
            name='admin_decision',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AddField(
            model_name='deletionaudit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deletionaudit',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deletionaudit',
            name='decision_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_audits_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deletionaudit',
            name='deletion_method',
            field=models.CharField(blank=True, choices=[('admin_direct', 'Admin Direct Delete'), ('teacher_request_approved', 'Teacher Request Approved')], max_length=40),
        ),
        migrations.AlterField(
            model_name='deletionaudit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deletionaudit',
            name='deleted_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_audits_direct_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deletionaudit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deleted', 'Permanently Deleted')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='deletionaudit',
            index=models.Index(fields=['status', 'created_at'], name='teachers_de_status_9c0ded_idx'),
        ),
        migrations.AddIndex(
            model_name='deletionaudit',
            index=models.Index(fields=['deletion_method', 'created_at'], name='teachers_de_deletio_143309_idx'),
        ),
        migrations.AddIndex(
            model_name='deletionaudit',
            index=models.Index(fields=['admin_decision', 'created_at'], name='teachers_de_admin_d_730149_idx'),
        ),
        migrations.RemoveField(
            model_name='deletionaudit',
            name='approved_by_admin',
        ),
    ]
