# Generated by Django 6.0.5 on 2026-09-07 02:44

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0007_batch_final_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=255)),
                ('chapter_description', models.CharField(blank=True, max_length=255)),
                ('chapter_order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=15)),
                ('delete_requested', models.BooleanField(default=False)),
                ('delete_requested_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.TextField(blank=True)),
                ('delete_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_chapters', to='admins.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_chapters', to='admins.teacher')),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_created_chapters', to=settings.AUTH_USER_MODEL)),
                ('delete_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_delete_requests', to='admins.teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_chapters', to='admins.subject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_chapters', to='admins.teacher')),
                ('updated_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_updated_chapters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['chapter_order'],
            },
        ),
        migrations.CreateModel(
            name='ChapterVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('video_description', models.TextField(blank=True)),
                ('video_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('video_order', models.PositiveIntegerField(default=1)),
                ('delete_requested', models.BooleanField(default=False)),
                ('delete_requested_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.TextField(blank=True)),
                ('delete_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_videos', to='admins.teacher')),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_created_videos', to=settings.AUTH_USER_MODEL)),
                ('delete_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_delete_requests', to='admins.teacher')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_videos', to='admins.teacher')),
                ('updated_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_updated_videos', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.coursechapter')),
            ],
            options={
                'ordering': ['video_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChapterQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=255)),
                ('quiz_description', models.TextField()),
                ('attempt_limit', models.PositiveIntegerField(default=1)),
                ('delete_requested', models.BooleanField(default=False)),
                ('delete_requested_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.TextField(blank=True)),
                ('delete_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_quizzes', to='admins.teacher')),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_created_quizzes', to=settings.AUTH_USER_MODEL)),
                ('delete_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_delete_requests', to='admins.teacher')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_quizzes', to='admins.teacher')),
                ('updated_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_updated_quizzes', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.coursechapter')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChapterPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=255)),
                ('pdf_description', models.TextField()),
                ('pdf_file', models.FileField(upload_to='course_pdfs/')),
                ('pdf_thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pdf_thumbnail')),
                ('pdf_order', models.PositiveIntegerField(default=1)),
                ('delete_requested', models.BooleanField(default=False)),
                ('delete_requested_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.TextField(blank=True)),
                ('delete_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_pdfs', to='admins.teacher')),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_created_pdfs', to=settings.AUTH_USER_MODEL)),
                ('delete_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_delete_requests', to='admins.teacher')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_pdfs', to='admins.teacher')),
                ('updated_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_updated_pdfs', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='courses.coursechapter')),
            ],
            options={
                'ordering': ['pdf_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChapterChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('order_changed', 'Order Changed'), ('status_changed', 'Status Changed'), ('delete_requested', 'Delete Requested'), ('delete_approved', 'Delete Approved'), ('delete_rejected', 'Delete Rejected'), ('restored', 'Restored')], max_length=30)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chapter_change_logs', to='admins.teacher')),
                ('changed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_chapter_change_logs', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='courses.coursechapter')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeletionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('chapter', 'Chapter'), ('video', 'Video'), ('pdf', 'PDF'), ('quiz', 'Quiz')], max_length=20)),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_name', models.CharField(max_length=255)),
                ('batch_name', models.CharField(blank=True, max_length=255)),
                ('subject_name', models.CharField(blank=True, max_length=255)),
                ('chapter_name', models.CharField(blank=True, max_length=255)),
                ('created_at_original', models.DateTimeField(blank=True, null=True)),
                ('delete_requested_at', models.DateTimeField(blank=True, null=True)),
                ('delete_request_reason', models.TextField(blank=True)),
                ('admin_decision', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('admin_response', models.TextField(blank=True)),
                ('admin_delete_reason', models.TextField(blank=True)),
                ('deletion_method', models.CharField(blank=True, choices=[('admin_direct', 'Admin Direct Delete'), ('teacher_request_approved', 'Teacher Request Approved')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deleted', 'Permanently Deleted')], default='pending', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_audits_created', to=settings.AUTH_USER_MODEL)),
                ('created_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_audits_created', to='admins.teacher')),
                ('decision_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_audits_decisions', to=settings.AUTH_USER_MODEL)),
                ('delete_requested_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_audits_requested', to='admins.teacher')),
                ('deleted_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_audits_direct_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PDFChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('name_changed', 'Name Changed'), ('description_changed', 'Description Changed'), ('file_changed', 'PDF File Changed'), ('thumbnail_changed', 'Thumbnail Changed'), ('order_changed', 'Order Changed'), ('delete_requested', 'Delete Requested'), ('delete_approved', 'Delete Approved'), ('delete_rejected', 'Delete Rejected'), ('restored', 'Restored')], max_length=40)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pdf_change_logs', to='admins.teacher')),
                ('changed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_pdf_change_logs', to=settings.AUTH_USER_MODEL)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='courses.chapterpdf')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuizChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('name_changed', 'Name Changed'), ('description_changed', 'Description Changed'), ('attempt_limit_changed', 'Attempt Limit Changed'), ('question_added', 'Question Added'), ('question_updated', 'Question Updated'), ('question_deleted', 'Question Deleted'), ('option_changed', 'Option Changed'), ('correct_answer_changed', 'Correct Answer Changed'), ('delete_requested', 'Delete Requested'), ('delete_approved', 'Delete Approved'), ('delete_rejected', 'Delete Rejected'), ('restored', 'Restored')], max_length=40)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz_change_logs', to='admins.teacher')),
                ('changed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_quiz_change_logs', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='courses.chapterquiz')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('marks', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.chapterquiz')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('option_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.quizquestion')),
            ],
            options={
                'ordering': ['option_label'],
            },
        ),
        migrations.CreateModel(
            name='VideoChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('name_changed', 'Name Changed'), ('description_changed', 'Description Changed'), ('file_changed', 'Video File Changed'), ('order_changed', 'Order Changed'), ('delete_requested', 'Delete Requested'), ('delete_approved', 'Delete Approved'), ('delete_rejected', 'Delete Rejected'), ('restored', 'Restored')], max_length=40)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='video_change_logs', to='admins.teacher')),
                ('changed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_video_change_logs', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='courses.chaptervideo')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='chaptervideo',
            index=models.Index(fields=['chapter', 'video_order'], name='courses_cha_chapter_60d2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterquiz',
            index=models.Index(fields=['chapter'], name='courses_cha_chapter_826205_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterpdf',
            index=models.Index(fields=['chapter', 'pdf_order'], name='courses_cha_chapter_927095_idx'),
        ),
        migrations.AddIndex(
            model_name='deletionaudit',
            index=models.Index(fields=['content_type', 'object_id'], name='courses_del_content_fcd525_idx'),
        ),
        migrations.AddIndex(
            model_name='deletionaudit',
            index=models.Index(fields=['status', 'created_at'], name='courses_del_status_91bc52_idx'),
        ),
        migrations.AddIndex(
            model_name='deletionaudit',
            index=models.Index(fields=['deletion_method', 'created_at'], name='courses_del_deletio_3e237e_idx'),
        ),
        migrations.AddIndex(
            model_name='deletionaudit',
            index=models.Index(fields=['admin_decision', 'created_at'], name='courses_del_admin_d_1ebc75_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizoption',
            constraint=models.UniqueConstraint(fields=('question', 'option_label'), name='unique_quiz_question_option_label'),
        ),
    ]
