# Generated by Django 6.0.5 on 2026-10-04 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_adminorderselection'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterpdf',
            options={'ordering': ['pdf_order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='chapterquiz',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='chaptervideo',
            options={'ordering': ['video_order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='coursechapter',
            options={'ordering': ['chapter_order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='deletionaudit',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deletionaudit',
            name='withdrawn_by_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_audits_withdrawn', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chapterchangelog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('order_changed', 'Order Changed'), ('status_changed', 'Status Changed'), ('delete_requested', 'Delete Requested'), ('delete_withdrawn', 'Delete Withdrawn'), ('delete_approved', 'Delete Approved'), ('delete_rejected', 'Delete Rejected'), ('restored', 'Restored')], max_length=30),
        ),
        migrations.AlterField(
            model_name='chapterchangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_changed', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chapterchangelog',
            name='changed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_admin_changed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapterpdf',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chapterpdf',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_admin_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapterpdf',
            name='delete_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_delete_requests', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chapterpdf',
            name='delete_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('withdrawn', 'Withdrawn'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='chapterpdf',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chapterpdf',
            name='updated_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_admin_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_admin_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='delete_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_delete_requests', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='delete_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('withdrawn', 'Withdrawn'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='updated_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_admin_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chaptervideo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chaptervideo',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_admin_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chaptervideo',
            name='delete_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_delete_requests', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chaptervideo',
            name='delete_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('withdrawn', 'Withdrawn'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='chaptervideo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='chaptervideo',
            name='updated_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_admin_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_admin_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='delete_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_delete_requests', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='delete_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('withdrawn', 'Withdrawn'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='updated_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_admin_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deletionaudit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('withdrawn', 'Withdrawn'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deleted', 'Permanently Deleted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pdfchangelog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('name_changed', 'Name Changed'), ('description_changed', 'Description Changed'), ('file_changed', 'PDF File Changed'), ('thumbnail_changed', 'Thumbnail Changed'), ('order_changed', 'Order Changed'), ('delete_requested', 'Delete Requested'), ('delete_withdrawn', 'Delete Withdrawn'), ('delete_approved', 'Delete Approved'), ('delete_rejected', 'Delete Rejected'), ('restored', 'Restored')], max_length=40),
        ),
        migrations.AlterField(
            model_name='pdfchangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_changed', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='pdfchangelog',
            name='changed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_admin_changed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizchangelog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('name_changed', 'Name Changed'), ('description_changed', 'Description Changed'), ('attempt_limit_changed', 'Attempt Limit Changed'), ('question_added', 'Question Added'), ('question_updated', 'Question Updated'), ('question_deleted', 'Question Deleted'), ('option_changed', 'Option Changed'), ('correct_answer_changed', 'Correct Answer Changed'), ('delete_requested', 'Delete Requested'), ('delete_withdrawn', 'Delete Withdrawn'), ('delete_approved', 'Delete Approved'), ('delete_rejected', 'Delete Rejected'), ('restored', 'Restored')], max_length=40),
        ),
        migrations.AlterField(
            model_name='quizchangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_changed', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='quizchangelog',
            name='changed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_admin_changed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videochangelog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('name_changed', 'Name Changed'), ('description_changed', 'Description Changed'), ('file_changed', 'Video File Changed'), ('order_changed', 'Order Changed'), ('delete_requested', 'Delete Requested'), ('delete_withdrawn', 'Delete Withdrawn'), ('delete_approved', 'Delete Approved'), ('delete_rejected', 'Delete Rejected'), ('restored', 'Restored')], max_length=40),
        ),
        migrations.AlterField(
            model_name='videochangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_changed', to='admins.teacher'),
        ),
        migrations.AlterField(
            model_name='videochangelog',
            name='changed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_admin_changed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deletionaudit',
            index=models.Index(fields=['subject_name', 'created_at'], name='courses_del_subject_ccee8b_idx'),
        ),
    ]
