# Generated by Django 6.0.5 on 2026-10-05 08:55

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_adminorderselection'),
        ('courses', '0003_remove_chapterpdf_courses_cha_chapter_927095_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=100)),
                ('pdf_description', models.CharField(max_length=250)),
                ('pdf_file', models.FileField(upload_to='course_pdfs/')),
                ('pdf_thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pdf_thumbnail')),
                ('pdf_order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='courses.coursechapter')),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_pdfs_created_as_admin', to=settings.AUTH_USER_MODEL)),
                ('created_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_pdfs_created_as_teacher', to='admins.teacher')),
            ],
            options={
                'ordering': ['pdf_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ChapterQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=100)),
                ('quiz_description', models.CharField(max_length=250)),
                ('quiz_order', models.PositiveIntegerField(default=1)),
                ('maximum_attempts', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.coursechapter')),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_quizzes_created_as_admin', to=settings.AUTH_USER_MODEL)),
                ('created_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_quizzes_created_as_teacher', to='admins.teacher')),
            ],
            options={
                'ordering': ['quiz_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ChapterVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100)),
                ('video_description', models.CharField(max_length=250)),
                ('video_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('video_thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video_thumbnail')),
                ('video_order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.coursechapter')),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_videos_created_as_admin', to=settings.AUTH_USER_MODEL)),
                ('created_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_videos_created_as_teacher', to='admins.teacher')),
            ],
            options={
                'ordering': ['video_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DeletionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('chapter', 'Chapter'), ('video', 'Video'), ('pdf', 'PDF'), ('quiz', 'Quiz')], max_length=20)),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_name', models.CharField(max_length=100)),
                ('batch_name', models.CharField(blank=True, max_length=255)),
                ('subject_name', models.CharField(blank=True, max_length=255)),
                ('chapter_name', models.CharField(blank=True, max_length=100)),
                ('original_created_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('request_reason', models.TextField(blank=True)),
                ('admin_decision', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('admin_response', models.TextField(blank=True)),
                ('admin_delete_reason', models.TextField(blank=True)),
                ('deletion_method', models.CharField(blank=True, choices=[('admin_direct', 'Admin Direct Delete'), ('teacher_request_approved', 'Teacher Request Approved')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_deletion_audits_created_as_admin', to=settings.AUTH_USER_MODEL)),
                ('created_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_deletion_audits_created_as_teacher', to='admins.teacher')),
                ('decision_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_deletion_decisions', to=settings.AUTH_USER_MODEL)),
                ('deleted_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_direct_deletions', to=settings.AUTH_USER_MODEL)),
                ('requested_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_deletion_requests', to='admins.teacher')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PDFChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('order_changed', 'Order Changed')], max_length=30)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pdf_changes_as_admin', to=settings.AUTH_USER_MODEL)),
                ('changed_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pdf_changes_as_teacher', to='admins.teacher')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='courses.chapterpdf')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuizChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('order_changed', 'Order Changed'), ('question_added', 'Question Added'), ('question_updated', 'Question Updated'), ('question_deleted', 'Question Deleted'), ('option_added', 'Option Added'), ('option_updated', 'Option Updated'), ('option_deleted', 'Option Deleted'), ('correct_answer_changed', 'Correct Answer Changed')], max_length=40)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz_changes_as_admin', to=settings.AUTH_USER_MODEL)),
                ('changed_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz_changes_as_teacher', to='admins.teacher')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='courses.chapterquiz')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('marks', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.chapterquiz')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('option_text', models.CharField(max_length=250)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.quizquestion')),
            ],
            options={
                'ordering': ['option_label'],
            },
        ),
        migrations.CreateModel(
            name='VideoChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('order_changed', 'Order Changed')], max_length=30)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='video_changes_as_admin', to=settings.AUTH_USER_MODEL)),
                ('changed_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='video_changes_as_teacher', to='admins.teacher')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='courses.chaptervideo')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='chapterpdf',
            constraint=models.UniqueConstraint(fields=('chapter', 'pdf_name'), name='unique_pdf_name_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='chapterquiz',
            constraint=models.UniqueConstraint(fields=('chapter', 'quiz_name'), name='unique_quiz_name_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='chaptervideo',
            constraint=models.UniqueConstraint(fields=('chapter', 'video_name'), name='unique_video_name_per_chapter'),
        ),
        migrations.AddIndex(
            model_name='deletionaudit',
            index=models.Index(fields=['content_type', 'object_id'], name='courses_del_content_fcd525_idx'),
        ),
        migrations.AddIndex(
            model_name='deletionaudit',
            index=models.Index(fields=['status', 'created_at'], name='courses_del_status_91bc52_idx'),
        ),
        migrations.AddIndex(
            model_name='deletionaudit',
            index=models.Index(fields=['deletion_method', 'created_at'], name='courses_del_deletio_3e237e_idx'),
        ),
        migrations.AddIndex(
            model_name='deletionaudit',
            index=models.Index(fields=['admin_decision', 'created_at'], name='courses_del_admin_d_1ebc75_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfchangelog',
            index=models.Index(fields=['pdf', 'changed_at'], name='courses_pdf_pdf_id_a71dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='quizchangelog',
            index=models.Index(fields=['quiz', 'changed_at'], name='courses_qui_quiz_id_2b3d02_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizoption',
            constraint=models.UniqueConstraint(fields=('question', 'option_label'), name='unique_quiz_question_option_label'),
        ),
        migrations.AddIndex(
            model_name='videochangelog',
            index=models.Index(fields=['video', 'changed_at'], name='courses_vid_video_i_f46f6f_idx'),
        ),
    ]
