# Generated by Django 6.0.5 on 2026-10-06 01:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_chapterpdf_chapterquiz_chaptervideo_deletionaudit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterchangelog',
            name='changed_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chapterchangelog',
            name='changed_by_role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pdfchangelog',
            name='changed_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pdfchangelog',
            name='changed_by_role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quizchangelog',
            name='changed_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quizchangelog',
            name='changed_by_role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='videochangelog',
            name='changed_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='videochangelog',
            name='changed_by_role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='chapterpdf',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='pdf'),
        ),
    ]
