# Generated by Django 6.0.5 on 2026-10-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_chapterchangelog_changed_by_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaptervideo',
            name='video_thumbnail',
        ),
    ]
