# Generated by Django 6.0.5 on 2026-10-06 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_adminorderselection'),
        ('courses', '0006_remove_chaptervideo_video_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterpdf',
            name='updated_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_pdfs_updated_as_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapterpdf',
            name='updated_by_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_pdfs_updated_as_teacher', to='admins.teacher'),
        ),
        migrations.AddField(
            model_name='chapterquiz',
            name='updated_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_quizzes_updated_as_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapterquiz',
            name='updated_by_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_quizzes_updated_as_teacher', to='admins.teacher'),
        ),
        migrations.AddField(
            model_name='chaptervideo',
            name='updated_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_videos_updated_as_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chaptervideo',
            name='updated_by_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_videos_updated_as_teacher', to='admins.teacher'),
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='updated_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_chapters_updated_as_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='updated_by_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_chapters_updated_as_teacher', to='admins.teacher'),
        ),
    ]
