# Generated by Django 5.2.7 on 2026-10-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_chapterpdf_updated_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterquiz',
            name='answering_time',
            field=models.PositiveIntegerField(default=30, help_text='Maximum time allowed for one quiz attempt, in minutes.'),
        ),
    ]
