# Generated by Django 5.2.7 on 2026-10-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_chapterquiz_answering_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='marks',
        ),
        migrations.AddField(
            model_name='chapterquiz',
            name='marks_per_question',
            field=models.PositiveIntegerField(default=1, help_text='Marks awarded for each question in this quiz.'),
        ),
    ]
