"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

from decouple import config
from pathlib import Path

from dotenv import load_dotenv

import os

load_dotenv()

# BASE DIRECTORY

BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY SETTINGS

SECRET_KEY = 'django-insecure-$r(eefie_c59rplz1*pfbd@0qnc3z1e5x#6u3x#9)_c^l3!sbf'

DEBUG = True

ALLOWED_HOSTS = []


# INSTALLED APPS

INSTALLED_APPS = [

    # DJANGO DEFAULT APPS

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # PROJECT APPS

    'accounts',
    'students',
    'admins',
    'home',
    'core',
    'teachers',

    # DJANGO ALLAUTH

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    'cloudinary',
    'cloudinary_storage',
]



# MIDDLEWARE

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'allauth.account.middleware.AccountMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ROOT URL CONFIGURATION

ROOT_URLCONF = 'config.urls'


# TEMPLATES

TEMPLATES = [

    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [BASE_DIR / 'templates'],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# WSGI APPLICATION

WSGI_APPLICATION = 'config.wsgi.application'


# DATABASE

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.postgresql',

        'NAME': 'neolearn_db',

        'USER': 'postgres',

        'PASSWORD': '12345',

        'HOST': 'localhost',

        'PORT': '5432',
    }
}


# PASSWORD VALIDATION

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# INTERNATIONALIZATION

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# STATIC FILES

STATIC_URL = 'static/'

STATICFILES_DIRS = [

    BASE_DIR / 'static',
]


# MEDIA FILES

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# DEFAULT PRIMARY KEY FIELD

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# EMAIL CONFIGURATION

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = config('EMAIL_HOST_USER')

EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')


# SESSION CONFIGURATION

SESSION_COOKIE_AGE = 3600

SESSION_SAVE_EVERY_REQUEST = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SESSION_COOKIE_HTTPONLY = True

CSRF_COOKIE_HTTPONLY = True

SESSION_COOKIE_SECURE = False

CSRF_COOKIE_SECURE = False


# DJANGO SITES

SITE_ID = 1


# LOGIN / LOGOUT REDIRECTS

LOGIN_URL = '/signin/'

LOGIN_REDIRECT_URL='/students/dashboard/'

LOGOUT_REDIRECT_URL = '/signin/'



# AUTHENTICATION BACKENDS

AUTHENTICATION_BACKENDS = (

    'django.contrib.auth.backends.ModelBackend',

    'allauth.account.auth_backends.AuthenticationBackend',
)


# DJANGO ALLAUTH SETTINGS

ACCOUNT_LOGIN_METHODS = {'username'}

ACCOUNT_SIGNUP_FIELDS = [

    'email*',

    'username*',

    'password1*',

    'password2*',
]

ACCOUNT_EMAIL_VERIFICATION = 'none'

ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False

ACCOUNT_LOGOUT_ON_GET = True

ACCOUNT_SESSION_REMEMBER = True

CLOUDINARY_STORAGE = {

    'CLOUD_NAME':os.getenv(
        'CLOUDINARY_CLOUD_NAME'
    ),

    'API_KEY':os.getenv(
        'CLOUDINARY_API_KEY'
    ),

    'API_SECRET':os.getenv(
        'CLOUDINARY_API_SECRET'
    ),
}

ACCOUNT_SESSION_REMEMBER = True

SOCIALACCOUNT_LOGIN_ON_GET = True


SOCIALACCOUNT_ADAPTER='accounts.adapters.GoogleAccountAdapter'

