# Generated by Django 6.0.5 on 2026-09-26 13:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0014_coupon_total_discount_given'),
        ('orders', '0004_remove_order_email_alter_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50)),
                ('coupon_description', models.TextField(blank=True, default='')),
                ('coupon_type', models.CharField(max_length=20)),
                ('discount_type', models.CharField(max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('maximum_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('per_user_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('applied_batch_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_coupon_snapshots', to='admins.batch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='orders.order')),
            ],
            options={
                'db_table': 'orders_order_coupon',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['order'], name='order_coupon_order_idx'), models.Index(fields=['coupon_code'], name='order_coupon_code_idx'), models.Index(fields=['coupon_type'], name='order_coupon_type_idx')],
            },
        ),
    ]
