# Generated by Django 6.0.5 on 2026-09-27 14:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='refund_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='RefundAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='processing', max_length=20)),
                ('requested_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('razorpay_refund_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='orders.refund')),
            ],
            options={
                'db_table': 'orders_refund_attempt',
                'ordering': ['attempt_number'],
                'indexes': [models.Index(fields=['refund', 'status'], name='refund_att_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('refund', 'attempt_number'), name='unique_refund_attempt_number')],
            },
        ),
    ]
