# Generated by Django 6.0.5 on 2026-09-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordercoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbatchpurchase',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('refunded', 'Refunded')], default='active', max_length=20),
        ),
    ]
