# Generated by Django 6.0.5 on 2026-09-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_refund_refund_number_refundattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_number',
            field=models.CharField(db_index=True, editable=False, max_length=40, unique=True),
        ),
    ]
