# Generated by Django 5.2.7 on 2026-09-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_studentbatchpurchase_status'),
        ('orders', '0007_alter_refund_refund_number'),
    ]

    operations = [
    ]
