# Generated by Django 6.0.5 on 2026-09-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_refundattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_source',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('scenario', 'Test Scenario')], db_index=True, default='razorpay', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='refundattempt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
