# Generated by Django 6.0.5 on 2026-10-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_payment_payment_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='refund_request_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True),
        ),
    ]
