# Generated by Django 6.0.5 on 2026-10-02 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_refund_refund_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_created', 'Order Created'), ('payment_created', 'Payment Created'), ('payment_processing', 'Payment Processing'), ('payment_succeeded', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('order_cancelled', 'Order Cancelled'), ('access_granted', 'Learning Access Granted'), ('access_revoked', 'Learning Access Revoked'), ('refund_requested', 'Refund Requested'), ('refund_processing', 'Refund Processing'), ('refund_completed', 'Refund Completed'), ('refund_rejected', 'Refund Rejected'), ('refund_reopened', 'Refund Reopened'), ('refund_failed', 'Refund Failed')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='orders.payment')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='orders.refund')),
            ],
            options={
                'db_table': 'orders_order_timeline_event',
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='order_timeline_order_created_idx'), models.Index(fields=['event_type', 'created_at'], name='order_timeline_type_created_idx')],
            },
        ),
    ]
