# Generated by Django 6.0.5 on 2026-10-02 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_ordertimelineevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ordertimelineevent',
            new_name='ord_timeline_order_idx',
            old_name='order_timeline_order_created_idx',
        ),
        migrations.RenameIndex(
            model_name='ordertimelineevent',
            new_name='ord_timeline_type_idx',
            old_name='order_timeline_type_created_idx',
        ),
    ]
